### ISSUE TITLE
Make Photo Editor Section Responsive

### ISSUE THREAD

**Issue by Shubhankar84** [Google-DSC-DMCE/ImageVoiceEditor-HacktoberFest-2023#1]
The Photo Editor section is not responsive, and it should be made responsive.

**Comment by Astraxx04** [comment]
Can you assign me this? I'll work on it

**Comment by Shubhankar84** [comment]
Assigned @Astraxx04

**Comment by vr1Ravi** [comment]
Can I also start working on it. Could you assign it to me

**Comment by shivendra8004** [comment]
@Shubhankar84 I am Working on this issue, Please assign it to me.
