### ISSUE TITLE
Fix 'Show Old' Button

### ISSUE THREAD

**Issue by Shubhankar84** [Google-DSC-DMCE/ImageVoiceEditor-HacktoberFest-2023#10]
The 'Show Old' button in the Photo Editor is not functioning as expected. It should be fixed.

**Comment by theavitw** [comment]
Hey @Shubhankar84 , 
I am looking forward to issue
kindly describe more about thisi ssue
and do share some visuals and link

**Comment by Shubhankar84** [comment]
@theavitw On click of 'Show old' button it should display the image that is uploaded by the user.

**Comment by vr1Ravi** [comment]
@Shubhankar84 can I start working on this issue

**Comment by vr1Ravi** [comment]
@Shubhankar84  could you check out my pull request
