### ISSUE TITLE
Enable Download Functionality in Modal Section

### ISSUE THREAD

**Issue by Shubhankar84** [Google-DSC-DMCE/ImageVoiceEditor-HacktoberFest-2023#3]
Users are unable to download edited images in the Photo Editor modal section. This functionality should be implemented and fixed.

**Comment by AyushmanSinghRajawat** [comment]
Hey @Shubhankar84, I would like to work on this issue as i have experience with similar functionality. Kindly assign me this issue.

**Comment by Shubhankar84** [comment]
Assigned @AyushmanSinghRajawat
