### ISSUE TITLE
Fix Sepia Checkbox Behavior

### ISSUE THREAD

**Issue by Shubhankar84** [Google-DSC-DMCE/ImageVoiceEditor-HacktoberFest-2023#4]
The Sepia checkbox only enables the effect, but unchecking it does not reflect the changes in the image. This behavior needs to be fixed.

**Comment by DIlkhush00** [comment]
Let me fix this issue. can you assign it to me?

**Comment by Shubhankar84** [comment]
Assigned to @DIlkhush00
